### ISSUE TITLE
Regarding thick lookups

### ISSUE THREAD

**Issue by NetOpWibby** [carlospaulino/node-whoisclient#1]
Long shot question considering this repo hasn't seen activity for six years, but has this been developed?

**Comment by carlospaulino** [comment]
Sorry. The feature was never developed, but you are more than welcome to open a PR any changes.

**Comment by NetOpWibby** [comment]
I’m just getting into WHOIS and have no idea how to determine the process of creating a thick lookup. Thanks for the quick response though, I’ll continue my research.
